services:
  app:
    build: .
    container_name: go_merch
    command: ./wait-for-db.sh db ./merch
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DB_PASSWORD: password
    restart: always

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: merch_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
